behaviors:
  DinoGame:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 1.0
        demo_path: Assets/Demonstrations/DinoDemo.demo
    keep_checkpoints: 5
    max_steps: 10e9
    threaded: true
    time_horizon: 1000
    summary_freq: 10000
